version: '3.8'

services:
  # PostgreSQL service
  db_postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # MySQL service
  db_mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # MongoDB service
  db_mongodb:
    image: mongo:latest
    container_name: mongodb-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_db
      MONGO_INITDB_ROOT_PASSWORD: mongodb_db
      MONGO_INITDB_DATABASE: mongodb_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
  # SQL Server service
  db_sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "sqlserver"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  sqlserver_data:
    driver: local
